/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/txEPnWNeBt9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Textarea } from "@/components/ui/textarea"

export function notes() {
  return (
    <div className="flex h-screen bg-[#333] text-white">
      <aside className="w-1/4 border-r border-gray-600">
        <div className="flex flex-col">
          <div className="p-4 border-b border-gray-600">
            <h1 className="text-xl font-bold">WEBNOTES</h1>
          </div>
          <ul className="flex flex-col space-y-2 overflow-y-auto p-4">
            <li className="flex flex-col">
              <span className="font-semibold truncate">The slow turtle...</span>
              <span className="text-xs text-gray-400">11/04/2024</span>
            </li>
            <li className="flex flex-col">
              <span className="font-semibold truncate">The clever rab...</span>
              <span className="text-xs text-gray-400">11/04/2024</span>
            </li>
          </ul>
        </div>
      </aside>
      <div className="flex flex-1 flex-col">
        <div className="flex p-4 border-b border-gray-600">
          <PlusIcon className="h-6 w-6 text-yellow-400" />
          <TrashIcon className="h-6 w-6 ml-auto text-red-500" />
        </div>
        <Textarea
          className="flex-1 bg-transparent p-4 text-white placeholder-gray-400"
          placeholder="Start typing your note here..."
        />
      </div>
    </div>
  )
}

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
